#add_library(Engine)
target_sources(
        ${PROJECT_NAME} PRIVATE
            include/Game.h
            src/Game.cpp
            include/Constants.h
            include/Actor.h
            src/Actor.cpp
            include/Component.h
            src/Component.cpp
            include/SpriteComponent.h
            src/SpriteComponent.cpp
            include/Math.h
            src/Math.cpp
            include/AnimSpriteComponent.h
            src/AnimSpriteComponent.cpp
            include/BGSpriteComponent.h
            src/BGSpriteComponent.cpp
            src/TileMapComponent.cpp
            include/TileMapComponent.h
            include/CSVUtils.h
            src/MoveComponent.cpp
            include/MoveComponent.h
            src/Random.cpp
            include/Random.h
            src/InputComponent.cpp
            include/InputComponent.h
            src/CircleComponent.cpp
            include/CircleComponent.h
            src/AIComponent.cpp
            include/AIComponent.h
            src/AIState.cpp
            include/AIState.h
            src/NavComponent.cpp
            include/NavComponent.h
            src/PhysicsMoveComponent.cpp
            include/PhysicsMoveComponent.h
            src/PhysicsInputComponent.cpp
            include/PhysicsInputComponent.h
            src/InputSystem.cpp
            include/InputSystem.h
            src/CameraComponent.cpp
            include/CameraComponent.h
)
#target_include_directories(Engine INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})